Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
  config.vm.define "nri-jmx-k8s"
  config.vm.hostname = "nri-jmx-k8s"
  config.vm.provider :virtualbox do |v|
      v.name = "nri-jmx-k8s"
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.memory = "2048"
      v.cpus = "4"
  end

  config.vm.provision "file", source: "./k8s", destination: "/home/vagrant/k8s"

  config.vm.provision "fix-network", type: "shell", path: "provision/fix-network.sh"
  config.vm.provision "install-microk8s", type: "shell", path: "provision/install-microk8s.sh"
  config.vm.provision "create-secret", type: "shell", path: "provision/create-secret.sh"
  config.vm.provision "deploy", type: "shell", path: "provision/deploy.sh"

end