integration_name: com.newrelic.jmx

instances:
  - name: jmx
    command: all_data
    arguments:
      jmx_host: 10.0.2.2
      jmx_port: 8008
      #jmx_user: admin
      #jmx_pass: admin
      key_store: /etc/pki/tomcatJMXClientKeyStore.key
      key_store_password: tomcat
      trust_store: /etc/pki/tomcatJMXClientTrustStore.key
      trust_store_password: tomcat
      collection_files: "/etc/newrelic-infra/integrations.d/jvm-metrics.yml,/etc/newrelic-infra/integrations.d/tomcat-metrics.yml"
    labels:
      env: staging
