apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-integration-cfg
data:
  jmx-config.yml: |
    ---
    # Run auto discovery to find pods with label "app=java"
    # https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery
    discovery:
      command:
        # Use the following optional arguments:
        # --namespaces: Comma separated list of namespaces to discover pods on
        # --tls: Use secure (TLS) connection
        # --port: Port used to connect to the kubelet. Default is 10255
        exec: /var/db/newrelic-infra/nri-discovery-kubernetes
        match:
          label.app: java
    integrations:
      - name: nri-jmx
        env:
          # Using the discovered IP as the host address
          JMX_HOST: ${discovery.ip}
          JMX_PORT: 9999
          COLLECTION_CONFIG: ${discovery.annotation.newrelic.config}
        labels:
          env: staging
