apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-agent-bundle
  labels:
    app: infra-agent-bundle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-agent-bundle
  template:
    metadata:
      labels:
        app: infra-agent-bundle
    spec:
      containers:
        - name: infra-k8s
          image: newrelic/infrastructure-k8s:latest
          volumeMounts:
            - name: nri-jmx-mount
              mountPath: "/etc/newrelic-infra/integrations.d"
              readOnly: true
          env:
            - name: NRIA_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: nriaLicenseKey
            - name: NRIA_VERBOSE
              value: "1"
            - name: IS_FORWARD_ONLY
              value: "true"
            - name: KUBERNETES_SERVICE_HOST
              value: "kubernetes.default.svc"
            - name: NRK8S_NODE_NAME
              value: "nri-jmx-k8s"
            - name: NRIA_CACHE_PATH
              value: "/tmp/nria_cache_path.json"
            - name: NRIA_PASSTHROUGH_ENVIRONMENT
              value: "NRIA_CACHE_PATH,KUBERNETES_SERVICE_HOST,NRK8S_NODE_NAME,KUBERNETES_SERVICE_PORT,CLUSTER_NAME,CADVISOR_PORT,KUBE_STATE_METRICS_URL,KUBE_STATE_METRICS_POD_LABEL,ETCD_TLS_SECRET_NAME,ETCD_TLS_SECRET_NAMESPACE,API_SERVER_SECURE_PORT,KUBE_STATE_METRICS_SCHEME,KUBE_STATE_METRICS_PORT,SCHEDULER_ENDPOINT_URL,ETCD_ENDPOINT_URL,CONTROLLER_MANAGER_ENDPOINT_URL,API_SERVER_ENDPOINT_URL,DISABLE_KUBE_STATE_METRICS,NETWORK_ROUTE_FILE"
          envFrom:
            - configMapRef:
                name: nr-env

      volumes:
        - name: nri-jmx-mount
          configMap:
            name: nri-integration-cfg
            items:
              - key: "jmx-config.yml"
                path: "jmx-config.yml"