name: Prerelease pipeline

on:
  release:
    types:
      - prereleased
    tags:
      - 'v*'

env:
  NRJMX_VERSION: '2.6.0' # Renovate automatically updates this dependencies to the latest release version. It will automatically merge minor and patch versions, while raising a pull request for major version updates.

jobs:
  test-integration-nix:
    name: Run integration tests on *Nix
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src/github.com/${{env.ORIGINAL_REPO_NAME}}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: src/github.com/${{env.ORIGINAL_REPO_NAME}}
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'src/github.com/${{env.ORIGINAL_REPO_NAME}}/go.mod'
      - name: Integration test
        env:
          GOPATH: ${{ github.workspace }}
        run: make integration-test

  pre-release:
    uses: newrelic/coreint-automation/.github/workflows/reusable_pre_release.yaml@NR-329534-add-input-windows-version-to-reusable-pre-release # TODO change back to v3
    with:
      tag: ${{ github.event.release.tag_name }}
      integration: "jmx"
      windows_goarch_matrix: '["amd64"]' # 386 not supported in jmx integrations
      win_package_type: exe # JMX integrations are shipped in .exe format
      publish_schema: "ohi-jmx" # ohi-jmx for integrations that bundle JMX on windows installers
      windows_download_nrjmx: true
      run_integration_nix: false
      dest_prefix: "test-resuable-prerelease-sairaj-2/"
      windows_version: "2019"
    secrets: inherit
