name: Release pipeline

on:
  release:
    types:
      - released
    tags:
      - 'v*'

jobs:
  release:
    uses: newrelic/coreint-automation/.github/workflows/reusable_on_release.yaml@v3
    with:
      integration: jmx
      tag: ${{ github.event.release.tag_name }}
      publish_schema: "ohi-jmx" # ohi-jmx for integrations that bundle JMX on windows installers
    secrets: inherit
